### ISSUE TITLE
Any Plans for Documentation or a Website?

### ISSUE THREAD

**Issue by n7trd** [holepunchto/bare#24]
Im really impressed by the bare-runtime. Are there plans to release documentation? I'm particularly interested in its architecture, available JavaScript runtimes and other information. Something akin to Holepunch's website, like a listing of modules and APIs would also be incredibly helpful. 

I think it's really interesting project beyond the Holepunch/Pear Runtime use case. 
Really incredible work! 👏

**Comment by kasperisager** [comment]
Thanks for the kind words! 🙌 A website is indeed coming, though I'm not yet sure when. Stay tuned!

**Comment by mafintosh** [comment]
Here is a list of builtin modules:

```
(the empty list)
```

Jokes aside, we will add a section of the pear docs to Bare as its an incredible piece of engineering, 95% made by @kasperisager.

**Comment by kasperisager** [comment]
With regards to documentation, the core API is documented here: https://github.com/holepunchto/bare?tab=readme-ov-file#api. We'll be expanding the other `bare-*` modules with API documentation as well.
