### ISSUE TITLE
[Question] Where is the initial require injected?

### ISSUE THREAD

**Issue by utanapishtim** [holepunchto/bare#26]
@kasperisager I'm trying to follow the code to understand where the global "require" is injected / defined and I can't find it. What am I missing? Trying to understand how the esm / cjs interop works.

**Comment by kasperisager** [comment]
_"There is no spoon"_
– That kid from the Matrix

The trick is that there is no global `require()`, or even a global module system, in Bare. It's all implemented in a user land module here: https://github.com/holepunchto/bare-module

The implementation of `require()`, for example, is found here: https://github.com/holepunchto/bare-module/blob/33535bc01c6bf5b1e1c3d8c6ceaff0c6e8eafed7/index.js#L480-L555

**Comment by utanapishtim** [comment]
I love it, but I'm still confused 😄! After reading further, it seems like: `link_bare_module(bare bare-module)` is where the actual module is getting injected into the bare bundle so that all the `*.js` files in this repo have access to `require`. I am assuming that `bare-dev` is doing some magic behind the scenes?

**Comment by kasperisager** [comment]
The `link_bare_module()` CMake function handles linking of native symbols, e.g. C functions exported from native addons, and so doesn't deal with JavaScript in any way.

The `require()` function you see in JavaScript modules in the `src/` directory is coming from `drive-bundler` (https://github.com/holepunchto/drive-bundler/blob/dc9323b6fde358f239ab93bebd56636285f9752f/index.js#L120-L122) and is _only_ available in the internal bootstrap bundle, which is a big JavaScript bundle used for initialising the `Bare.*` APIs. The bootstrap bundle is defined in the build definition here:

https://github.com/holepunchto/bare/blob/1a886c4fae29a399a76adb049cd2f1784b4bcf49/CMakeLists.txt#L133-L137

It's compiled to a C header file and then run during `bare_runtime_setup()` to initialise the `Bare.*` APIs:

https://github.com/holepunchto/bare/blob/1a886c4fae29a399a76adb049cd2f1784b4bcf49/src/runtime.c#L1109-L1115

The `require()` function you see in all other modules outside of those in the `src/` directory is coming from `bare-module`.

**Comment by utanapishtim** [comment]
@kasperisager thank you so much for this explanation!

**Comment by kasperisager** [comment]
Pleasure! 😄
