### ISSUE TITLE
Addon examples and ARM/Risc-V CPUs for AI Accelerators

### ISSUE THREAD

**Issue by bonseyes-vlab** [holepunchto/bare#29]
Hello,

We would to try bare on ARM/risc-v processors and have a use case of calling AI models using addons.

Do you have an example of using addons?

**Comment by kasperisager** [comment]
We don't officially support running Bare on RISC-V processors, but ARM has first class support on macOS and Linux. All of our native addons ship with macOS and Linux ARM prebuilds as well.
